sudo: required

services:
        - docker

before_install:
        - docker build -t piyush4upiy/docker-react -f Dockerfile.dev .

script:
        - docker run piyush4upiy/docker-react npm run test -- --coverage
